spring:
  config:
    import: optional:file:.env[.properties]
  banner:
    charset: utf-8
    location: templates/banner/banner.txt
  datasource:
    url: ${DB_DEV_URL}
    username: ${DB_DEV_USERNAME}
    password: ${DB_DEV_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        format_sql: true
aws:
  region: ${AWS_REGION}
  s3:
    buckets:
      users: ${BUCKET_NAME}